template_path: remote-templates/vpc.yaml
stack_name: vpc
parameters:
  VpcSubnetPrefix: "10.6"
  VpcName: sagevpc
  PrivateSubnetZones: "us-east-1c,us-east-1d,us-east-1e"
  PublicSubnetZones: "us-east-1c,us-east-1d,us-east-1e"
hooks:
  before_update:
    - !cmd "aws --profile {{ var.profile }} s3 cp s3://{{ environment_variable.AdminCentralInfraCfBucket }}/aws-infra/master/vpc.yaml ./remote-templates/vpc.yaml"
